book_create:
  path: /books
  controller: App\UI\Controller\Book\CreateBookController
  methods: [ POST ]

book_index:
  path: /books
  controller: App\UI\Controller\Book\GetBooksController
  methods: [ GET ]

book_find:
  path: /books/{id}
  controller: App\UI\Controller\Book\GetBookController
  methods: [ GET ]

book_delete:
  path: /books/{id}
  controller: App\UI\Controller\Book\DeleteBookController
  methods: [ DELETE ]